### ISSUE TITLE
Upgrade sequelize

### ISSUE THREAD

**Issue by r1oga** [zkitter/zkitterd#58]
`sequelize` is used as ORM library in zkitterd.
Versions < 6.21.2 are vulnerable to SQL injection attacks.
https://security.snyk.io/vuln/SNYK-JS-SEQUELIZE-2959225

Raw queries with string replacement are especially used for the [posts search endpoint.](https://github.com/zkitter/zkitterd/blob/48965e9fc2805e86fd3c04fd1d80e8d4f98da482/src/models/posts.ts#L515)

I don't expect breaking changes as it is a minor upgrade (didn't check though).

**Comment by 0xtsukino** [comment]
https://github.com/zkitter/zkitterd/blob/main/package.json
sequelize at 6.26 on master
